apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-20T00:48:11.485399615Z"
    description: A Helm chart for Kubernetes
    digest: f4c89d522f1603f67319d169e33e0893174818cfa77ccf212e417985d2f9075c
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-11-20T00:48:11.486671164Z"
    description: A Helm chart for hub agent
    digest: 044644767573d7be4c05ad63b3d8657b3a268413d7ce1680be8c0de035212572
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-11-20T00:48:11.487264855Z"
    description: Helm chart for member agent.
    digest: 1ae7e5d07fa72f88adb39db8e1a399116c8f7c8a04fc7ef2a76121cb47547e75
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-20T00:48:11.484193048Z"
