apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-02-02T10:40:57.743687795Z"
    description: A Helm chart for Kubernetes
    digest: 643ca2c6a3a2b7dbd083fa3c72b96a820c18a4c24b2d6c666b2542fba4cc9e9c
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-02-02T10:40:57.745416082Z"
    description: A Helm chart for hub agent
    digest: 21bd0cccb189bc66b2473d66a7890dddbcf2835114f20d0c88fbd7a916268011
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-02-02T10:40:57.745845163Z"
    description: Helm chart for member agent.
    digest: 75975d03fd50855ede0419371c9c3d96594fa47fc1c64afb06caffdef05738be
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-02T10:40:57.743150342Z"
