apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-02-06T20:15:37.651112673Z"
    description: A Helm chart for Kubernetes
    digest: e2ab009e09192bb06def41587fc2c8594b3daa1aaa0851c098af66c0bc5baf4c
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-02-06T20:15:37.652823741Z"
    description: A Helm chart for hub agent
    digest: 8aa4af0a4fad1aa1ab7c143852b8f6d5c94cb9d0521c28b2aa07398b8919d963
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-02-06T20:15:37.65330012Z"
    description: Helm chart for member agent.
    digest: 3a8dbdc0f0d28a11cc4943f10c174878bdb65f489643ddbbf86a9442ddc2b795
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-06T20:15:37.650300246Z"
