apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-01-22T18:14:39.908734838Z"
    description: A Helm chart for Kubernetes
    digest: 55510e57d506df96822e705cd3db74a57f3f59201661a28b0da37d23cc52d159
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-01-22T18:14:39.910299048Z"
    description: A Helm chart for hub agent
    digest: d2d8b02a037efe6149ea654bfb840b1bb4c02c5ae610a6a3a9a1b9608cce0beb
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-01-22T18:14:39.91077754Z"
    description: Helm chart for member agent.
    digest: 4a7e0a9d678f8975881ee5d5361d86d279d6548f3c5eb985f3537352510ed3da
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-22T18:14:39.908195843Z"
