apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-08T09:06:04.007689698Z"
    description: A Helm chart for Kubernetes
    digest: eb0e0208ed7db6219d74dbee7fe8f47eadd1bb0be5ee4fa796d7b599f827bc0e
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-08T09:06:04.008426024Z"
    description: A Helm chart for hub agent
    digest: 2c73c685da4e1771a9a7b391720b9a083035d62168dc7c0c39c732201db2d9ae
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-12-08T09:06:04.008844908Z"
    description: Helm chart for member agent.
    digest: 9e8896c563202818aadf4438b4471061303cb5cf3beb19e5e67a051314f9b1bb
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-08T09:06:04.007230209Z"
