apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-15T18:01:24.994580229Z"
    description: A Helm chart for Kubernetes
    digest: 5c3c438fdbeb0e962c1230cf0e0924d8471290056d0ce40ffce7e520fcc3faeb
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-15T18:01:24.99533802Z"
    description: A Helm chart for hub agent
    digest: c0ea7b7f66cf9568c9c419467da10d7e6a70014fa372d407fa9e5b5bc70583b5
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-12-15T18:01:24.995733181Z"
    description: Helm chart for member agent.
    digest: 19618a968e2e3d820ec920f4d0d03c64dba3be904d7585f38fbf65eec57977d5
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-15T18:01:24.994074279Z"
