apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-01-26T10:36:11.078973031Z"
    description: A Helm chart for Kubernetes
    digest: c8b1c3123bb60cdb1a77472fdfd2e3cf1fc0b22c60198e80121037f4b4e4e488
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-01-26T10:36:11.080349511Z"
    description: A Helm chart for hub agent
    digest: 48ff35a440e05a4623cdd6553a13fd91f93e581266e215c5cedb7f81319c4c7b
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-01-26T10:36:11.080766072Z"
    description: Helm chart for member agent.
    digest: f2211cbe69a600d368606234c79562004b8a1ca80f0e3bc3037d6a83e7c232a0
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-26T10:36:11.07827981Z"
