apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-10T22:32:15.764955273Z"
    description: A Helm chart for Kubernetes
    digest: b6add45ce356ea1a4a335dc01d2eb0c6cdc1f7f93955ead1f47148ee867d4a73
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-10T22:32:15.765738177Z"
    description: A Helm chart for hub agent
    digest: f6663c3712dba1fb11d90b611b01f2b4b1ad99fee9bec80d601e39ceaecef0ff
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-12-10T22:32:15.766156379Z"
    description: Helm chart for member agent.
    digest: f4a35ef8c776bdf7d680073579fc619ad889c7305b41a725e16dd09c1f137f6e
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-10T22:32:15.764457042Z"
