apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-24T09:32:04.963670579Z"
    description: A Helm chart for Kubernetes
    digest: d1c0ce72c1c0131c8b9748e2bc833a9c0efed4217fc06f94f3163bc990d198f2
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-11-24T09:32:04.964447807Z"
    description: A Helm chart for hub agent
    digest: 194eb60dd1fce213991c4981db45fde68abe86a7366f2b22131ffca4988f14ef
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-11-24T09:32:04.964891013Z"
    description: Helm chart for member agent.
    digest: 3fff9e9ae1ba84c52ec410732bcbc80a8504972c1d284b247511de0b3c9088f1
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-24T09:32:04.96243081Z"
