apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-05T02:12:20.869039645Z"
    description: A Helm chart for Kubernetes
    digest: 1176f18def92637ffde62c35da374e02457f5f0e8d838fe61fe765915fd07e5f
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-05T02:12:20.869833767Z"
    description: A Helm chart for hub agent
    digest: 54253d4b329d8e37788a0a1352fd3b0d8572fd814b6d2649a7caeaa6674a5660
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-12-05T02:12:20.870271264Z"
    description: Helm chart for member agent.
    digest: 3c40790dc1747ba290b9ff1f58acdd40d7e82ed96025b3e4e2590d1b258f4a7b
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-05T02:12:20.867777727Z"
