apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-04T20:42:06.840494482Z"
    description: A Helm chart for Kubernetes
    digest: 1af1c67f2d95b1b932d9468445011c0e8db18fa5ce456623f57871801e9cc713
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-04T20:42:06.841312463Z"
    description: A Helm chart for hub agent
    digest: c61dc6f4300b0425914e065d7503e8b138ead615f7c70670d392f2e9c1713d66
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-12-04T20:42:06.841745257Z"
    description: Helm chart for member agent.
    digest: 7d35ec8b46bdaa56b975448bf09e80c444c2a72ccde33dfb4894ea7d6f1b5575
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-04T20:42:06.839948958Z"
