apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-10T17:14:34.437910521Z"
    description: A Helm chart for Kubernetes
    digest: 2430257ff48aaaa1d67e3171dd4d9bc50cd7781b7a144f03d8e7d08ad88cbf8b
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-11-10T17:14:34.438572053Z"
    description: A Helm chart for hub agent
    digest: 25499207e977151909a6530a499867c5d229e40ac99f9026901cf3aea4f1de3e
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-11-10T17:14:34.439047676Z"
    description: Helm chart for member agent.
    digest: ba56f54600fbb74c2d395dbe08dd1e76fe67a89facde14c16e4f430e02b869f1
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-10T17:14:34.437391462Z"
