apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-15T09:05:39.34708986Z"
    description: A Helm chart for Kubernetes
    digest: 905339114eec0ab0dad61c0a45d9fc8ccba3ab184cfc9c155824c575204cb5fe
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-15T09:05:39.34782908Z"
    description: A Helm chart for hub agent
    digest: acd6c9ce13eb70a42ba7f50de4937c8b1104845ab4af4973fc66c473ee0e6914
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-12-15T09:05:39.348270214Z"
    description: Helm chart for member agent.
    digest: b812a34c35ea064b6a4c29ff093f5a4e4aeaa816f9cdaafb8e93170a4e58296d
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-15T09:05:39.346616316Z"
